using Octokit;
using AIPRReviewer.Models;
using DotNetEnv;

namespace AIPRReviewer.Agents;

public class CommenterAgent
{
    private readonly string _agentName = "CommenterAgent";
    private readonly GitHubClient _github;
    private readonly string _repoOwner;
    private readonly string _repoName;

    public CommenterAgent()
    {
        var token = Env.GetString("GITHUB_TOKEN");
        var repoFull = Env.GetString("GITHUB_REPO");

        var parts = repoFull.Split('/');
        _repoOwner = parts[0];
        _repoName = parts[1];

        _github = new GitHubClient(new ProductHeaderValue("AIPRReviewer"))
        {
            Credentials = new Credentials(token)
        };
    }

    private string FormatSummaryComment(ReviewResult review)
    {
        var verdictEmoji = review.OverallVerdict switch
        {
            "APPROVE" => "✅",
            "REQUEST_CHANGES" => "❌",
            _ => "💬"
        };

        var riskEmoji = review.RiskLevel switch
        {
            "LOW" => "🟢",
            "MEDIUM" => "🟡",
            "HIGH" => "🔴",
            _ => "⚪"
        };

        var comment = "## 🤖 AI Code Review\n\n";
        comment += $"**Verdict:** {verdictEmoji} {review.OverallVerdict}\n";
        comment += $"**Risk Level:** {riskEmoji} {review.RiskLevel}\n\n";
        comment += "### Summary\n";
        comment += $"{review.OverallSummary}\n\n";
        comment += "### What was done well ✨\n";
        comment += $"{review.PositiveFeedback}\n\n";
        comment += $"### Issues Found ({review.Issues.Count})\n";

        for (int i = 0; i < review.Issues.Count; i++)
        {
            var issue = review.Issues[i];
            var severityEmoji = issue.Severity switch
            {
                "CRITICAL" => "🔴",
                "MAJOR" => "🟠",
                "MINOR" => "🟡",
                "SUGGESTION" => "🔵",
                _ => "⚪"
            };

            var shortComment = issue.Comment.Length > 100
                ? issue.Comment[..100] + "..."
                : issue.Comment;

            comment += $"\n{i + 1}. {severityEmoji} **{issue.Severity}** in `{issue.Filename}` — {shortComment}";
        }

        if (review.Suggestions.Any())
        {
            comment += "\n\n### Suggestions 💡\n";
            foreach (var suggestion in review.Suggestions)
                comment += $"- {suggestion}\n";
        }

        comment += "\n\n---\n*Review generated by AI PR Review Agent (C# + Claude)*";

        return comment;
    }

    public async Task<bool> RunAsync((PRData prData, ReviewResult review)? reviewData)
    {
        if (reviewData == null)
        {
            Console.WriteLine($"[{_agentName}] No review data. Stopping.");
            return false;
        }

        var (prData, review) = reviewData.Value;

        Console.WriteLine($"[{_agentName}] Posting review to PR #{prData.PrNumber}...");

        var summaryComment = FormatSummaryComment(review);
        await _github.Issue.Comment.Create(
            _repoOwner,
            _repoName,
            prData.PrNumber,
            summaryComment
        );
        Console.WriteLine($"[{_agentName}] Posted main review comment");

        foreach (var issue in review.Issues.Where(i =>
            i.Severity == "CRITICAL" || i.Severity == "MAJOR"))
        {
            var issueComment = $"### {issue.Severity} Issue — {issue.IssueType}\n\n";
            issueComment += $"**File:** `{issue.Filename}`\n";
            issueComment += $"**Problem:** {issue.Comment}";

            await _github.Issue.Comment.Create(
                _repoOwner,
                _repoName,
                prData.PrNumber,
                issueComment
            );
            Console.WriteLine($"[{_agentName}] Posted issue for {issue.Filename}");

            await Task.Delay(500);
        }

        Console.WriteLine($"[{_agentName}] All comments posted!");
        return true;
    }
}